### ISSUE TITLE
Søkefunksjon

### ISSUE THREAD

**Issue by Haakenlid** [Haakenlid/tassen#40]
Alternativene jeg vurderer er Watson og Haystack. Jeg mistenker at det er litt mer å sette seg inn i med Haystack, men at det mer state-of-the-art. Watson funker visst veldig bra med postgresql, så det er jo lovende. Tror jeg satser på Watson i utgangspunktet og eventuelt vurderer å flytte over til Haystack hvis Watson ikke funker bra nok.

https://github.com/etianen/django-watson

https://github.com/django-haystack/django-haystack

**Comment by Velmont** [comment]
Haystack i seg sjølv er nok truleg ikkje nok, du må vel velja backend du vil bruka for det òg?  T.d. Woosh eller Elasticsearch.  Elasticsearch er ganske hot stuffs, brukar det til forskjellege ting på jobb - men hovudoppgåva til ei avis er jo ikkje naudsynt søk :)

Watson såg interessant ut som ei løysing for å få noko godt nok på plass enkelt, kjapt og greit.  Takk for den :)

**Comment by Haakenlid** [comment]
Takk for tipset. Det er litt vanskelig å vite hva forskjellen mellom de ulike haystack-backends egentlig er. Jeg har inntrykk av at Elasticsearch er det mest populære, så det ville nok vært det naturlige valget.

Søk er nødvendig funksjonalitet, men det trenger ikke å være svimlende raskt på en nettside som Universitas. Jeg mistenker at watson er raskt nok i massevis. Litt usikker på hvilke konkrete fordeler Haystack kan gi.

**Comment by Haakenlid** [comment]
Watson skal funke veldig bra med postgresql.
https://github.com/etianen/django-watson/wiki/Database-support#postgresql

**Comment by Haakenlid** [comment]
Har fått på plass watson. Ser ut til å være rask nok i massevis. Har ikke laget noen skikkelig side for søkeresultater ennå. 
Ser ut til at det kan være ganske enkelt å lage en ajax-løsning der søkeresultater vises uten å laste siden på nytt.

**Comment by Haakenlid** [comment]
Søkefunksjonen er på plass. Det er rom for finpuss på hvordan visningen ser ut. Men det får være issue #37
