### ISSUE TITLE
Google analytics-telling

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassen#55]
Jeg tror denne koden må inn på nettsida for at Google analytics skal greie å telle trafikken på den.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62582744-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by Haakenlid** [comment]
Har lagt inn analytics. Det ser ut til å funke nå.
