### ISSUE TITLE
Feil med Facebook-lenker

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassen#56]
Av en eller annen grunn har det blitt noe galt med sakene vi deler på Facebook etter at jeg delte denne: http://universitas.no/nyheter/60547/trener-minst-vinner-mest

Alle sakene delt etterpå får ingressen fra denne ene saken i FB-visninga

**Comment by Haakenlid** [comment]
Facebook vet nok ikke helt hvor de skal lete etter ingressen. Ingressen blir kanskje hentet fra en av sakene som er lenket fra "nyeste saker" i toppmenyen. 

Uansett tror jeg at det kan fikses ved å få på plass Open Graph metadata #57

**Comment by PetterFlottum** [comment]
Høres ut som en god plan! Er det noe du rekker å prioritere i dag, eller tar det lang tid?

**Comment by Haakenlid** [comment]
Det skal være fort gjort.

**Comment by PetterFlottum** [comment]
Tipp topp!

**Comment by Haakenlid** [comment]
Skal funke nå. Du kan kontrollere at det funker som det skal fra denne nettsiden. Lim inn url til artikkelen som skal sjekkes i feltet «Input URL»
https://developers.facebook.com/tools/debug/og/object/

**Comment by Haakenlid** [comment]
De sakene som allerede har blitt delt på Facebook får ikke oppdatert ingressen, ser det ut som. Sakene blir oppdatert med byline i facebook-innlegget, noe som manglet tidligere. 

Kanskje administrator for facebook-gruppa har mulighet til oppdatere eller endre innleggene på en eller annen måte.
