### ISSUE TITLE
Redigering og oppdatering av info-sider på universitas.no

### ISSUE THREAD

**Issue by Haakenlid** [Haakenlid/tassen#59]
Det er noen sider som inneholder info om avisa for lesere og annonsører. De blir klippet og limt fra den gamle nettsiden. Jeg kommer etterhvert til å lage et opplegg sånn at dette kan endres fra adminsidene omtrent som vanlige artikler, men det er ikke så høyt prioritert ennå. 

Foreløpig må alle endringer i tekstene legges inn manuelt i kildefilene. 

Hvis det er noe som er feil her så kan jeg fikse det hvis noen gir beskjed (helst som svar på denne issuen )

---
## Om Universitas
Universitas er Norges største studentavis.
Avisen har et opplag på 14 000, og kommer ut 35 ganger i året.

Universitas mottar støtte fra Studentsamskipnaden i Oslo og Akershus (SiO), og alle studenter som betaler semesteravgift er dermed med på å støtte Universitas økonomisk. Papirutgaven av Universitas distribueres rundt på læresteder tilknyttet SiO.

Universitas legges også ut ved studentbyene under SiO. Redaksjonen består av fire heltidsansatte og en rekke journalister, fotografer, sideuttegnere etc. som jobber frilans.

Våre redaksjonslokaler finner du i andre etasje i Eilert Sunds barnehage, Moltke Moes vei 33. 

Vil du abonnere og få Universitas hjem til deg eller til din arbeidsplass, ta kontakt med daglig leder Louise Faldalen Prytz på tlf. 22 85 33 36, eller se under for andre måter å komme i kontakt.

### Generell kontaktinfo
Telefon: 22 85 33 36
Faks: 22 85 32 74
Postadresse: Boks 89 Blindern, 0314 Oslo
Besøksadresse: Moltke Moes vei 33

Redaksjonen for tips, leserbrev og generelle hevendelser.
«Hva skjer?» for å tipse om arrangement til plakaten

Redaktør Geir Molnes
Nettredaktør Petter Fløttum
Daglig leder Louise Faldalen Prytz
Redaksjonsleder Vilde Sagstad Imeland
Annonseansvarlig Geir Dorp
Systemutviklingsansvarlig Håken Lid

### Utgivelsesplan
Neste avis er nr 15 og kommer ut 2015-05-06.

Se hele planen. (lenke)

### Annonsering
Kontakt Geir Dorp, eller les mer om annonsering. (lenke)

---

## Annonser i Universitas
Avisen har et opplag på 14 000 og distribueres til læresteder tilknyttet SiO, blant annet Universitetet i Oslo, Handelshøyskolen BI, Høgskolen i Oslo og Akershus, Idrettshøgskolen, Musikkhøgskolen, Politihøgskolen, Kunsthøgskolen og Menighetsfakultetet. 

---

### Leserbrev i Universitas
Universitas tar gjerne imot leserinnlegg. Undertegn med fullt navn og legg ved et bilde av deg selv. Redaksjonen forbeholder seg retten til å forkorte innlegg og til å publisere innleggene på internett. Manuskripter som er sendt til flere redaksjoner benyttes ikke. Debattinnlegg sendes til debatt@universitas.no

**Comment by Haakenlid** [comment]
@geirmolnes Hei. Kan du sjekke at denne infoen er riktig og ikke utdatert?

**Comment by geirmolnes** [comment]
Infoen er oppdatert nå.

**Comment by Haakenlid** [comment]
Infoen under annonsering stemmer ikke. Opplagstallet og skolene tilknytta SiO er ikke oppdatert.

**Comment by geirmolnes** [comment]
Korrekt. Har oppdatert informasjonen nå.

**Comment by Haakenlid** [comment]
http://universitas.no/om_universitas/
http://universitas.no/annonser/
