### ISSUE TITLE
Flere crop-alternativer for bilder

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassen#60]
Det bør være flere enn to utsnittsvalg for bilder i sakene.

**Comment by Haakenlid** [comment]
I starten tror jeg det er best med noen standardstørrelser. Det blir fort litt hulter til bulter hvis mange bilder i en sak har ulike bildestørrelser.

**Comment by hadahva** [comment]
Det burde være mulig å vise bilder ucroppet, spesielt i bildekaruseller og i saker som har flere bilder (type reportasjesaker og bildetunge kultursaker). Dette gjelder i alle fall bilder som er lagt inn i saken, men burde kanskje også være et alternativ for hovedbildet?

Måten høydebilder vises på må også legges om, nå er de veldig små. Er det mulig å ha de små, og så ha muligheten til å forstørre dem ved å trykke?

Jeg ønsker meg selvfølgelig også en fullskjermvisning av bilder.

Høydebilder burde kanskje også kunne være en del av en bildekarusell uten å bli croppet til breddebilder, men det er kanskje avhengig av en fullskjerm- eller forstørrelsesfunksjon.

**Comment by Haakenlid** [comment]
Nå er det flere valg på størrelse. Hvis det er bildekarusell blir alle bildene i samme format som det som ligger først. 

I tillegg kan man få større bredde på bilder, sitater og sånn ved å bruke tegnet = i markup.
