### ISSUE TITLE
Bytte «Omverden» til «Utenriks»

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassen#61]
Seksjonen «omverden» byttet navn til «utenriks» for noen måneder siden. Det bør den gjøre på nett også

**Comment by Haakenlid** [comment]
Den ligger som en artikkeltype under seksjonen 'Nyheter'
Har endret forsidesakene sånn at de har temaord og vignett 'utenriks'.

Oversikt:
http://universitas.no/nyheter/utenriks/

Endre artikkeltype:
http://universitas.no/admin/stories/storytype/4/

**Comment by PetterFlottum** [comment]
Tipp topp!

5. mai 2015 kl. 09.49 skrev Håken Lid <notifications@github.com>:
