### ISSUE TITLE
Flere faner i menyen

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassen#64]
Etter flere tilbakemeldinger, tror jeg vi bør legge noen flere faner inn i menyen enn bare nyhet, kultur, debatt og magasin.

Det bør være en egen fane for engelske saker, anmeldelser og for annonsører.

I tillegg lurer jeg på om det kanskje er best at disse er i fullbredde hele tiden og med tekst i. Det blit litt lite intuitivt slik det er nå.

Annonseknappen er nok den viktigste først. Har snakket med Geir Dorp, og skjønt det slik at det er litt for vanskelig å finne fram for annonsører i dag.

**Comment by Haakenlid** [comment]
Menyen som den er nå er litt provisorisk. Jeg har en del planer om hvordan den skal bli, og vil gjerne få på plass bedre mobilvisning og noen andre funksjoner før vi legger til greier der. 

Det er alt for mange nettaviser med overlesset meny. Det blir vanskeligere å finne fram jo flere greier man har i menyen. 

![image](https://cloud.githubusercontent.com/assets/1686266/7492617/f4d27bb6-f3f9-11e4-82e9-2a5c610d4471.png)

Siden menyen må funke på flere skjermstørrelser og visninger, så må endringer planlegges en del før de puttes på plass. Det er ganske komplisert samspill mellom innhold, funksjon og design der. 

Tenker det er noe vi kan ha et møte og diskutere en gang i løpet av mai. Vi bør ta en gjennomgang av seksjons-strukturen også, og sørge for at de ulike artikkeltypene hører til i riktig seksjon.

**Comment by PetterFlottum** [comment]
Kan en mulig inspirasjon være Studvests meny? http://www.studvest.no/ Ikke for overlesset og ganske ryddig, synes jeg.

**Comment by PetterFlottum** [comment]
Kan Studvest være en inspirasjon? Den er litt stor, men ganske ryddig: http://www.studvest.no/

Og ja, Aftenposten funker også. DB bør vi ikke se til.

**Comment by Haakenlid** [comment]
Jeg er åpen for å diskutere det, men det er en del av designet som trenger et helhetlig grep og som jeg ikke vil bygge opp litt etter litt. Sånne ting blir fort bare rotete. I papiravisa er det gjort en del små endringer i løpet av de siste årene som sikkert hadde gode grunner enkeltvis, men som til sammen gjør at avisa ser mer rotete ut enn den burde.
